### ISSUE TITLE
pose estimation

### ISSUE THREAD

**Issue by hassan-shehawy** [BlackJocker1995/Apriltagcsharp#1]
so this code can only detect the tags, without actually giving the pose of detected tag, correct?

**Comment by BlackJocker1995** [comment]
yes，this code only  gives the homography matrix of tags，if you want get the tag's pose needed to know scale of your camera。



发自我的小米手机
在 Hassan Shehawy <notifications@github.com>，2018年5月4日 下午8:40写道：

so this code can only detect the tags, without actually giving the pose of detected tag, correct?

**Comment by hassan-shehawy** [comment]
yes I did that function, thanks :)
