### ISSUE TITLE
objectpoints order

### ISSUE THREAD

**Issue by hassan-shehawy** [BlackJocker1995/Apriltagcsharp#2]
hi
do you have an order for the output detected object points (the 4 points defining the tag)? Because I got some weird results when I run solvepnp with the camera matrix and distortion vector

**Comment by BlackJocker1995** [comment]
when you get tagdetection.you can get it's public value named points which is an array of   point.those points are quad'corners.

**Comment by hassan-shehawy** [comment]
yes I understand. My question is about the order of these points, because I need to know which point correspond to what point in the object coordinate system when using solvepnp

**Comment by BlackJocker1995** [comment]
tagdetection's value named rotation can give you information about rotation of tag relatived to origin direction.if you want to know order of points ,you can use that value. for example，if rotation is 2，that means index 2 of points is first point.

**Comment by hassan-shehawy** [comment]
Yes, that’s it what I needed. Thanks
