### ISSUE TITLE
Repo has no license terms

### ISSUE THREAD

**Issue by BenjaminPelletier** [BlackJocker1995/Apriltagcsharp#3]
Could you add a license under which this repo may be used?  I would like to use it in my project :)  If you don't know which license to use, the [MIT license](https://en.wikipedia.org/wiki/MIT_License) makes it very easy to reuse software tools.

**Comment by BlackJocker1995** [comment]
sure,i will create it

**Comment by BenjaminPelletier** [comment]
Awesome, thanks!
